package io.composelive.nodes.foundation.common

import androidx.compose.runtime.Immutable
import kotlinx.serialization.Serializable

@[Immutable Serializable]
public data class TextStyle(
    val color: Color = Color.Unspecified,
    val fontSize: TextUnit = TextUnit.Unspecified,
    val fontWeight: FontWeight? = null,
    val fontStyle: FontStyle? = null,
    val fontSynthesis: FontSynthesis? = null,
    val fontFamily: FontFamily? = null,
    val fontFeatureSettings: String? = null,
    val letterSpacing: TextUnit = TextUnit.Unspecified,
    val baselineShift: BaselineShift? = null,
    val textGeometricTransform: TextGeometricTransform? = null,
    val localeList: List<Locale>? = null,
    val background: Color = Color.Unspecified,
    val textDecoration: TextDecoration? = null,
    val shadow: Shadow? = null,
    val drawStyle: DrawStyle? = null,
    val textAlign: TextAlign = TextAlign.Unspecified,
    val textDirection: TextDirection = TextDirection.Unspecified,
    val lineHeight: TextUnit = TextUnit.Unspecified,
    val textIndent: TextIndent? = null,
    val lineHeightStyle:LineHeightStyle? = null,
    val lineBreak: LineBreak = LineBreak.Unspecified,
    val hyphens: Hyphens = Hyphens.Unspecified,
    val textMotion: TextMotion? = null,
) {
    public fun merge(
        color: Color? = null,
        fontSize: TextUnit? = null,
        fontWeight: FontWeight? = null,
        fontStyle: FontStyle? = null,
        fontSynthesis: FontSynthesis? = null,
        fontFamily: FontFamily? = null,
        fontFeatureSettings: String? = null,
        letterSpacing: TextUnit? = null,
        baselineShift: BaselineShift? = null,
        textGeometricTransform: TextGeometricTransform? = null,
        localeList: List<Locale>? = null,
        background: Color? = null,
        textDecoration: TextDecoration? = null,
        shadow: Shadow? = null,
        drawStyle: DrawStyle? = null,
        textAlign: TextAlign? = null,
        textDirection: TextDirection? = null,
        lineHeight: TextUnit? = null,
        textIndent: TextIndent? = null,
        lineHeightStyle:LineHeightStyle? = null,
        lineBreak: LineBreak? = null,
        hyphens: Hyphens? = null,
        textMotion: TextMotion? = null,
    ): TextStyle {
        return copy(
            color = color ?: this.color,
            fontSize = fontSize ?: this.fontSize,
            fontWeight = fontWeight ?: this.fontWeight,
            fontStyle = fontStyle ?: this.fontStyle,
            fontSynthesis = fontSynthesis ?: this.fontSynthesis,
            fontFamily = fontFamily ?: this.fontFamily,
            fontFeatureSettings = fontFeatureSettings ?: this.fontFeatureSettings,
            letterSpacing = letterSpacing ?: this.letterSpacing,
            baselineShift = baselineShift ?: this.baselineShift,
            textGeometricTransform = textGeometricTransform ?: this.textGeometricTransform,
            localeList = localeList ?: this.localeList,
            background = background ?: this.background,
            textDecoration = textDecoration ?: this.textDecoration,
            shadow = shadow ?: this.shadow,
            drawStyle = drawStyle ?: this.drawStyle,
            textAlign = textAlign ?: this.textAlign,
            textDirection = textDirection ?: this.textDirection,
            lineHeight = lineHeight ?: this.lineHeight,
            textIndent = textIndent ?: this.textIndent,
            lineHeightStyle = lineHeightStyle ?: this.lineHeightStyle,
            lineBreak = lineBreak ?: this.lineBreak,
            hyphens = hyphens ?: this.hyphens,
            textMotion = textMotion ?: this.textMotion,
        )
    }
}

public val DefaultTextStyle: TextStyle = TextStyle()
