package io.composelive.nodes.foundation

import app.cash.redwood.schema.Schema

@Schema(
    [
        // Widgets
        Box::class,
        Column::class,
        Row::class,
        FlowRow::class,
        FlowColumn::class,
        Spacer::class,
        LazyGrid::class,
        LazyGridItems::class,
        Pager::class,
        AnimatedVisibility::class,
        ClickReceiver::class,
        TextField::class,
        Text::class,
        AnnotatedText::class,
        AsyncImage::class,
        Button::class,
        MotionProgressHolder::class,
        ReuseRoot::class,
        ReuseNode::class,
        AsyncBoxWithConstraints::class,
        LazyList::class,
        LazyListItems::class,
        SelectionContainer::class,
        RenderedEffectLauncher::class,
        ShallowWrapper::class,

        // Modifiers
        Reuse::class,
        Padding::class,
        AlignHorizontally::class,
        AlignVertically::class,
        Align::class,
        Width::class,
        Height::class,
        Weight::class,
        FillMaxWidth::class,
        FillMaxHeight::class,
        AspectRatio::class,
        Background::class,
        Clip::class,
        StickyHeader::class,
        Shimmer::class,
        Alpha::class,
        DefaultMinSize::class,
        WrapContentHeight::class,
        LayoutId::class,
        HorizontalScroll::class,
        BrushBackground::class,
        Clickable::class,
        IntrinsicHeight::class,
        IntrinsicWidth::class,
    ],
)
interface Foundation
